version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ThucAnNhanhdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8089:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456
    depends_on:
      - mysql

  nguoi-dung-service:
    build: ./nguoi-dung-service
    container_name: nguoi-dung-container
    ports:
      - "8084:8080"
    depends_on:
      - mysql

  mon-an-service:
    build: ./mon-an-service
    container_name: mon-an-container
    ports:
      - "8085:8080"
    depends_on:
      - mysql

  chung-thuc-service:
    build: ./chung-thuc-service
    container_name: chung-thuc-container
    ports:
      - "8086:8080"

  hoa-don-service:
    build: ./hoa-don-service
    container_name: hoa-don-container
    ports:
      - "8087:8080"
    depends_on:
      - mysql
      - nguoi-dung-service
      - mon-an-service
      - chung-thuc-service

  quan-ly-dat-thuc-an-nhanh-client:
    build: ./quan-ly-dat-thuc-an-nhanh-client
    container_name: quan-ly-dat-thuc-an-nhanh-client-container
    ports:
      - "8088:8080"
    depends_on:
      - hoa-don-service

volumes:
  mysql_data: