events {}

http {
    server {
        listen 80;

        location = / {
            return 302 /TrangChu;
        }

        location / {
            proxy_pass http://quan-ly-dat-thuc-an-nhanh-client:8080/;
        }
    }
}